version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8098:80
    links:
      - fpm
    volumes:
      - ./:/var/www/corpruschess
    networks:
      - internal
  fpm:
    build:
      context: .
      dockerfile: ./docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/corpruschess
    links:
      - mysql
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal
  mysql:
    image: mysql:5.7
    ports:
    - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravelchess
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
